name: ClockIn

on:
  push:
    branches: 
      - master
  watch:
    types: started
  schedule:
    - cron: '28 17,0 * * *'

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install python3
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install python3
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT2: ${{ secrets.ACCOUNT2 }}
          PASSWORD2: ${{ secrets.PASSWORD2 }}
          MAILKEY: ${{ secrets.MAILKEY }}
        run: |
          python3 clock-in.py ${ACCOUNT} ${PASSWORD} ${MAILKEY}
          python3 clock-in.py ${ACCOUNT2} ${PASSWORD2} ${MAILKEY}
